"""
Domain models for job-app backend.

SINGLE SOURCE OF TRUTH for all Pydantic v2 models.
All models use ConfigDict(extra="ignore") for forward compatibility.

Requirements: 1.3, 2.2, 2.5, 3.1, 4.6, 5.1, 20.1, 20.3
"""

from datetime import datetime
from typing import List, Optional
from enum import Enum
from pydantic import BaseModel, ConfigDict, Field


# ============================================================================
# CV PARSING AND PROFILE MODELS
# ============================================================================


class ExperienciaLaboral(BaseModel):
    """Work experience entry from CV."""

    puesto: str = Field(..., description="Job title")
    empresa: str = Field(..., description="Company name")
    duracion: str = Field(..., description="Duration (e.g., '2 years', 'Jan 2020 - Dec 2021')")
    descripcion: str = Field(..., description="Job description and responsibilities")
    tecnologias: List[str] = Field(default_factory=list, description="Technologies used")

    model_config = ConfigDict(extra="ignore")


class Educacion(BaseModel):
    """Education entry from CV."""

    titulo: str = Field(..., description="Degree or certification title")
    institucion: str = Field(..., description="Institution name")
    ano: str = Field(..., description="Year or year range")
    especializacion: Optional[str] = Field(
        default=None, description="Specialization or focus area"
    )

    model_config = ConfigDict(extra="ignore")


class Proyecto(BaseModel):
    """Project entry from CV."""

    nombre: str = Field(..., description="Project name")
    descripcion: str = Field(..., description="Project description")
    tecnologias: List[str] = Field(default_factory=list, description="Technologies used")
    url: Optional[str] = Field(default=None, description="Project URL (optional)")

    model_config = ConfigDict(extra="ignore")


class Certificacion(BaseModel):
    """Certification entry from CV."""

    nombre: str = Field(..., description="Certification name")
    emisor: str = Field(..., description="Issuing organization")
    ano: str = Field(..., description="Year obtained")

    model_config = ConfigDict(extra="ignore")


class PerfilEstructurado(BaseModel):
    """User's structured CV profile, parsed from raw CV text.

    This is the primary data structure for storing user's professional information.
    """

    experiencia: List[ExperienciaLaboral] = Field(
        default_factory=list, description="Work experience entries"
    )
    educacion: List[Educacion] = Field(default_factory=list, description="Education entries")
    proyectos: List[Proyecto] = Field(
        default_factory=list, description="Project entries"
    )
    certificaciones: List[Certificacion] = Field(
        default_factory=list, description="Certification entries"
    )
    skills: List[str] = Field(..., description="Technical skills")
    lenguajes: List[str] = Field(
        default_factory=list, description="Languages spoken/read"
    )

    model_config = ConfigDict(extra="ignore")


class RolesSuggestions(BaseModel):
    """Role suggestions for a user based on their profile.

    Generated by Bedrock based on resumen.
    Not persisted; returned directly to client.
    """

    suggestions: List[str] = Field(..., description="List of 5-7 suggested job roles")

    model_config = ConfigDict(extra="ignore")


# ============================================================================
# COMPANY AND SUBSCRIPTION MODELS
# ============================================================================


class PlatformaEnum(str, Enum):
    """Job posting platform types."""

    GREENHOUSE = "greenhouse"
    LEVER = "lever"
    JSONLD = "jsonld"
    HTML = "html"
    MANUAL = "manual"


class ScanStatusEnum(str, Enum):
    """Scan job status."""

    OK = "OK"
    FAILED = "FAILED"
    EMPTY_SOSPECHOSO = "EMPTY_SOSPECHOSO"
    EMPTY_LEGITIMO = "EMPTY_LEGITIMO"


class Empresa(BaseModel):
    """Company in the shared catalog.

    Global, shared across all users. One entry per unique careers URL (keyed by SHA-256 hash).
    """

    companyId: str = Field(..., description="SHA-256 hash of normalized careers URL (64 hex chars)")
    nombre: str = Field(..., description="Company display name")
    careersUrl: str = Field(..., description="Careers page URL")
    plataforma: PlatformaEnum = Field(..., description="Job posting platform")
    lastScannedAt: Optional[datetime] = Field(
        default=None, description="Timestamp of last scan"
    )
    lastScanStatus: Optional[ScanStatusEnum] = Field(
        default=None, description="Status of last scan"
    )
    lastVacancyCount: int = Field(
        default=0, description="Number of vacancies found in last scan"
    )
    consecutiveFailures: int = Field(
        default=0, description="Count of consecutive failed scan attempts"
    )
    boardToken: Optional[str] = Field(
        default=None,
        description="Board token for greenhouse/lever API (extracted from careersUrl or set manually)",
    )
    ultimoOrigenExitoso: Optional[str] = Field(
        default=None,
        description="Last successful extraction origin: 'board_api' | 'json_ld' | 'html_llm'",
    )
    createdAt: datetime = Field(
        default_factory=datetime.utcnow, description="Timestamp when company was added"
    )

    model_config = ConfigDict(extra="ignore")


class Suscripcion(BaseModel):
    """User subscription to a company.

    Tracks which companies a user is monitoring for job openings.
    """

    userId: str = Field(..., description="User ID (from JWT sub claim)")
    companyId: str = Field(..., description="Company ID (SHA-256 hash)")
    activa: bool = Field(
        default=True, description="Whether subscription is active (soft delete pattern)"
    )
    addedAt: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp when subscription was added or reactivated",
    )
    updatedAt: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp of last update to this subscription",
    )

    model_config = ConfigDict(extra="ignore")


class ScanJob(BaseModel):
    """Async scan job tracker.

    Represents a user-initiated multi-company scan.
    Managed by orquestador and scan-worker Lambdas.
    """

    scanJobId: str = Field(..., description="Unique scan job identifier")
    userId: str = Field(..., description="User ID who initiated the scan")
    status: str = Field(..., description="Job status (RUNNING, COMPLETED, PARTIAL)")
    companiesCount: int = Field(..., description="Total companies to scan")
    completedCount: int = Field(default=0, description="Number of companies scanned")
    failedCompanies: List[str] = Field(
        default_factory=list, description="Company IDs that failed to scan"
    )
    startedAt: datetime = Field(
        default_factory=datetime.utcnow, description="Timestamp when scan started"
    )
    updatedAt: datetime = Field(
        default_factory=datetime.utcnow, description="Timestamp of last update"
    )

    model_config = ConfigDict(extra="ignore")


# ============================================================================
# PERFILES TABLE SHAPE
# ============================================================================


class Perfiles(BaseModel):
    """User profile as stored in DynamoDB Perfiles table.

    Single document per userId (PK).
    Contains structured experience, AI-generated summary, suggested/active roles, and version.
    """

    userId: str = Field(..., description="User ID (PK)")
    perfilEstructurado: Optional[PerfilEstructurado] = Field(
        default=None, description="Structured CV profile"
    )
    resumenParaMatching: Optional[str] = Field(
        default=None,
        description="≤500-word summary for scoring (generated by worker, read-only from backend-core)",
    )
    resumenGenerationStatus: Optional[str] = Field(
        default=None,
        description="Generation status: 'pending' | 'complete' | 'failed' | null (managed by worker)",
    )
    cargosSugeridos: List[str] = Field(
        default_factory=list, description="Suggested roles from Bedrock"
    )
    cargosActivos: List[str] = Field(
        default_factory=list, description="Roles selected by user (1-10 items)"
    )
    profileVersion: int = Field(
        default=0, description="Profile version (incremented on save or role change)"
    )
    updatedAt: datetime = Field(
        default_factory=datetime.utcnow, description="Timestamp of last profile update"
    )

    model_config = ConfigDict(extra="ignore")


class ResumenParaMatchingOutput(BaseModel):
    """Salida de Bedrock para la generación de resumenParaMatching.

    Validada antes de persistir en Perfiles.resumenParaMatching. El límite de
    ≤500 palabras es una instrucción de prompt (no un max_length de Pydantic,
    que mide caracteres, no palabras).

    Requirements: 2.3
    """

    resumen: str = Field(
        ..., min_length=1, description="Resumen del perfil, objetivo ≤500 palabras"
    )

    model_config = ConfigDict(extra="ignore")


# ============================================================================
# USUARIO-VACANTE TABLE SHAPE
# ============================================================================


class UsuarioVacante(BaseModel):
    """User-vacancy relationship and scoring details.

    PK: userId (S), SK: {companyId}#{vacancyId} (S). No GSI.
    Requirements: 1.9, 1.10, 2.1, 3.7, 4.1, 5.6, 6.3, 17.5, 18.1
    """

    userId: str = Field(..., description="User ID (from JWT sub claim)")
    companyId: str = Field(..., description="Company ID (SHA-256 hash)")
    vacancyId: str = Field(..., description="Vacancy ID (SHA-256 of normalized URL)")
    estado: str = Field(
        ...,
        description="'nueva' | 'vista' | 'aplicada' | 'filtered_out'",
    )
    score: Optional[int] = Field(
        default=None,
        ge=0,
        le=100,
        description="Match score 0-100; null if filtered_out or pending",
    )
    scoreDetalle: Optional[dict] = Field(
        default=None,
        description="ScoringResult dict (veredicto, coincidencias, faltantes, resumen)",
    )
    scoreProfileVersion: Optional[int] = Field(
        default=None,
        description="Profile version when score was computed (for staleness detection)",
    )
    cvAtsTexto: Optional[str] = Field(
        default=None,
        description="Generated ATS-optimized CV text for this vacancy",
    )
    cvGeneratedAt: Optional[datetime] = Field(
        default=None,
        description="Timestamp when cvAtsTexto was generated",
    )
    appliedAt: Optional[datetime] = Field(
        default=None,
        description="Timestamp when user marked this vacancy as applied",
    )
    createdAt: datetime = Field(
        default_factory=datetime.utcnow, description="Timestamp when record was created"
    )
    updatedAt: datetime = Field(
        default_factory=datetime.utcnow, description="Timestamp of last update"
    )

    model_config = ConfigDict(extra="ignore")


class ScoringMessage(BaseModel):
    """Message payload for SQS_Scoring queue.

    Published by Scan_Worker, consumed by Scoring_Worker.
    Requirement 12.4: One message per (userId, Vacante) pair of NEW vacancy.
    """

    userId: str = Field(..., description="User ID (from JWT sub claim)")
    vacancyId: str = Field(..., description="Vacancy ID (SHA-256 of normalized URL, 64 hex chars)")

    model_config = ConfigDict(extra="ignore")


class BedRockExtractVacancyOutput(BaseModel):
    """Pydantic model for validating Bedrock's vacancy extraction output.

    Used by Manual_Vacancy_Service to validate the LLM extraction of job posting fields
    from pasted text.
    Requirements: 3.1, 10.1
    """

    titulo: str = Field(..., min_length=1, description="Job title extracted from text")
    descripcion: str = Field(..., min_length=1, description="Job description extracted from text")
    modalidad: str = Field(default="sin_dato", description="Work modality (remote/hybrid/onsite/sin_dato)")
    ubicacion: str = Field(default="", description="Job location extracted from text")

    model_config = ConfigDict(extra="ignore")


class CVATSOutput(BaseModel):
    """Output from Bedrock for ATS-optimized CV generation.

    Requirements: 5.4, 10.1
    """

    texto: str = Field(..., min_length=1, description="Plain text CV-ATS (no tables, no columns)")

    model_config = ConfigDict(extra="ignore")


class ScoringResult(BaseModel):
    """Output from Bedrock_Client scoring invocation.

    Validates score, veredicto, coincidencias, faltantes, resumen.
    Requirements: 1.10, 17.1
    """

    score: int = Field(..., ge=0, le=100, description="Match score 0-100")
    veredicto: str = Field(
        ..., description="'excelente' | 'buen_encaje' | 'parcial' | 'bajo'"
    )
    coincidencias: List[str] = Field(
        default_factory=list, description="Matched requirements/skills"
    )
    faltantes: List[str] = Field(
        default_factory=list, description="Missing requirements/skills"
    )
    resumen: str = Field(..., description="Short match summary")

    model_config = ConfigDict(extra="ignore")


class Vacante(BaseModel):
    """Job posting / vacancy.

    Global, shared across all users. Keyed by vacanteSha256 (SHA-256 of normalized job posting URL).
    Managed by scan-worker Lambda.
    """

    vacanteSha256: str = Field(..., description="SHA-256 hash of normalized job posting URL")
    companyId: str = Field(..., description="Company ID (reference to Empresas table)")
    titulo: str = Field(..., description="Job title")
    descripcion: str = Field(..., description="Job description")
    requisitos: List[str] = Field(
        default_factory=list, description="Job requirements/keywords"
    )
    modalidad: str = Field(
        default="sin_dato", description="Employment type (remote/hybrid/onsite/sin_dato)"
    )
    ubicacion: str = Field(default="", description="Job location")
    url: str = Field(..., description="Original job posting URL")
    plataforma: PlatformaEnum = Field(..., description="Platform where posting was found")
    origen: str = Field(default="automated", description="Origin: 'automated' or 'manual'")
    crawledAt: datetime = Field(
        default_factory=datetime.utcnow, description="When the posting was crawled"
    )
    verificadaAt: Optional[datetime] = Field(
        default=None, description="When posting was verified to still exist"
    )
    missCount: int = Field(
        default=0, description="Number of failed verification attempts"
    )
    cerrada: bool = Field(
        default=False,
        description="Whether posting has been marked as closed (missCount >= 2, origen != 'manual')",
    )

    model_config = ConfigDict(extra="ignore")


# ============================================================================
# ENTRADAS TABLE SHAPE
# ============================================================================


class Entrada(BaseModel):
    """User entry (questions or interview notes) for a vacancy.

    PK: {userId}#{companyId}#{vacancyId} (S), SK: entryId (S, ULID). No GSI.
    Requirements: 6.3
    """

    pk: str = Field(
        ..., description="Partition key: {userId}#{companyId}#{vacancyId}"
    )
    entryId: str = Field(..., description="Entry ID (ULID string)")
    tipo: str = Field(
        ..., description="'preguntas' | 'nota_entrevista'"
    )
    contenido: str = Field(..., description="Entry content text")
    createdAt: datetime = Field(
        default_factory=datetime.utcnow, description="Timestamp when entry was created"
    )

    model_config = ConfigDict(extra="ignore")


class SuggestedAnswerOutput(BaseModel):
    """Output from Bedrock for suggested interview answer."""

    respuesta: str = Field(..., min_length=1, description="Suggested interview answer")

    model_config = ConfigDict(extra="ignore")
